### ISSUE TITLE
Error on user.changeLanguage:after

### ISSUE THREAD

**Issue by Daandelange** [hananils/kirby-tracker#2]
Hey,
Trying out your plugin, I noticed a copy/paste mistake here, leading the panel to crash on this action.
https://github.com/hananils/kirby-tracker/blob/297ed3e1f9feb634242a9274ba1ce5438a15ea22/index.php#L151
Replacing with `$tracker->track('user', 'changeLanguage', $newUser, $oldUser, 'language');` obviously fixes it. :)

**Comment by nilshoerrmann** [comment]
Thanks @Daandelange, this should be fixed now!
